services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.backend  # Specify the backend Dockerfile
    ports:
      - "5000:5000"  # Expose the backend on port 5000
    volumes:
      - ./apps/server:/app/server  # Map the server code
      - ./podcast-feed:/app/podcast-feed  # Map the podcast-feed directory
    networks:
      - my_network
    environment:
      FLASK_DEBUG: "1"  # Set Flask to development mode

  frontend:
    build:
      context: ./apps/client
      dockerfile: Dockerfile.frontend  # Specify the frontend Dockerfile
    ports:
      - "3000:3000"  # Expose the frontend on port 3000
    volumes:
      - ./apps/client:/app  # Mount the frontend source code
      - ./podcast-feed:/app/podcast-feed
    networks:
      - my_network
    environment:
      REACT_APP_API_URL: "http://backend:5000"  # Point frontend to backend API

networks:
  my_network:
    driver: bridge
