# Flask API Dockerfile

# Use a Python base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
COPY ../../requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy the Flask app code into the container
COPY apps/server /app/server

# Expose the port that Flask will run on
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "/app/server/src/app.py"]