name: Build and Run Podcast Docker Container

on:
  push:
    branches: [ "main" ]
    paths:
      - 'podcast-feed/podcast.yaml' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'podcast-feed/podcast.yaml'

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to get access to the files
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker Buildx (for building multi-platform images, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t podcast-generator -f apps/server/Dockerfile .

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: |
          docker run --name podcast-container podcast-generator

