name: Generate Podcast Feed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate_feed:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to get access to the files
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python version

      # Step 3: Install dependencies (make sure your requirements.txt includes the necessary packages)
      - name: Install dependencies
        run: |
          pip install -r apps/server/requirements.txt  # Install the dependencies

      # Step 4: Run the script to generate the podcast feed
      - name: Run podcast feed generation
        run: |
          python apps/server/src/services/feed.py

      - name: Commit and push podcast.xml
        run: |
          git config --global user.name "Edward Wills"
          git config --global user.email "ewills1@sheffield.ac.uk"
          git add podcast.xml
          git commit -m "Update podcast feed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
